easy_admin:
    site_name: "Initiaville"
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    entities:
        Project:
            class: App\Entity\Project
            list:
                actions: ['-edit', '-new', 'show']
                fields:
                    - 'title'
                    - 'excerpt'
                    - 'createdAt'
                    - 'user'
            show:
                actions: ['-edit']

        Category:
            class: App\Entity\Category
            form:
                fields :
                    - { property: 'label', label: 'Nom de la catégorie'}
        User:
            class: App\Entity\User
            list:
                actions: ['-edit', '-new', 'show']
            show:
                actions: ['-edit']
                fields:
                    - 'email'
                    - 'firstname'
                    - 'lastname'
                    - {property: 'roles', type: 'simple_array'}
                    - 'projects'

        City:
            class: App\Entity\City
            image_base_path: '%uploads_url%'
            list:
                fields:
                    - 'name'
                    - { property: 'picture', type: 'image' }
            form:
                fields:
                    - 'name'
                    - { property: 'picturePath', label: 'Photo', type: 'file_upload', type_options: { upload_dir: 'public\uploads\cities' } }

        Comment:
            class: App\Entity\Comment
            list:
                actions: ['-new']
            form:
                fields:
                    - 'title'
                    - 'content'